//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hci_apoteka.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sr_la {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sr_la() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hci_apoteka.Languages.sr-la", typeof(sr_la).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblik.
        /// </summary>
        internal static string availablestrength {
            get {
                return ResourceManager.GetString("availablestrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barkod.
        /// </summary>
        internal static string barcode {
            get {
                return ResourceManager.GetString("barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osnovne informacije.
        /// </summary>
        internal static string basicinformation {
            get {
                return ResourceManager.GetString("basicinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Račun.
        /// </summary>
        internal static string bill {
            get {
                return ResourceManager.GetString("bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Računi.
        /// </summary>
        internal static string bills {
            get {
                return ResourceManager.GetString("bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži.
        /// </summary>
        internal static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nabavna cijena.
        /// </summary>
        internal static string buyingprice {
            get {
                return ResourceManager.GetString("buyingprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        internal static string cancle {
            get {
                return ResourceManager.GetString("cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KASA.
        /// </summary>
        internal static string cashregister {
            get {
                return ResourceManager.GetString("cashregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodajna cijena.
        /// </summary>
        internal static string cellingprice {
            get {
                return ResourceManager.GetString("cellingprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifrati.
        /// </summary>
        internal static string chipers {
            get {
                return ResourceManager.GetString("chipers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proizvođači.
        /// </summary>
        internal static string companies {
            get {
                return ResourceManager.GetString("companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proizvođač.
        /// </summary>
        internal static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj račun.
        /// </summary>
        internal static string createbill {
            get {
                return ResourceManager.GetString("createbill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doza.
        /// </summary>
        internal static string dosage {
            get {
                return ResourceManager.GetString("dosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaposleni.
        /// </summary>
        internal static string employees {
            get {
                return ResourceManager.GetString("employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakture.
        /// </summary>
        internal static string inovice {
            get {
                return ResourceManager.GetString("inovice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMBG.
        /// </summary>
        internal static string jmbg {
            get {
                return ResourceManager.GetString("jmbg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavi se.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijava u sistem.
        /// </summary>
        internal static string logintothesystem {
            get {
                return ResourceManager.GetString("logintothesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijek.
        /// </summary>
        internal static string medicine {
            get {
                return ResourceManager.GetString("medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijekovi.
        /// </summary>
        internal static string medicines {
            get {
                return ResourceManager.GetString("medicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv lijeka.
        /// </summary>
        internal static string namemedicine {
            get {
                return ResourceManager.GetString("namemedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova faktura.
        /// </summary>
        internal static string newinvoice {
            get {
                return ResourceManager.GetString("newinvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redni broj.
        /// </summary>
        internal static string noinvoice {
            get {
                return ResourceManager.GetString("noinvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikal.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Količina.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kasa.
        /// </summary>
        internal static string sales {
            get {
                return ResourceManager.GetString("sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalihe.
        /// </summary>
        internal static string stock {
            get {
                return ResourceManager.GetString("stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UKUPAN IZNOS.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukupan iznos.
        /// </summary>
        internal static string totalprice {
            get {
                return ResourceManager.GetString("totalprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        internal static string town {
            get {
                return ResourceManager.GetString("town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaci nisu validni.
        /// </summary>
        internal static string typeddatanotvalid {
            get {
                return ResourceManager.GetString("typeddatanotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip korisnika.
        /// </summary>
        internal static string usertype {
            get {
                return ResourceManager.GetString("usertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipovi korisnika.
        /// </summary>
        internal static string usertypes {
            get {
                return ResourceManager.GetString("usertypes", resourceCulture);
            }
        }
    }
}
